name: Update Favorite Video List

on:
  push:
    branches: [ main ]
  schedule:
    - cron: 0 9 */1 * *
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y ffmpeg
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        mkdir download
    - name: Run Python Scripts
      env:
        BILIBILI_UID: ${{ secrets.BILIBILI_UID }}
        ONEDRIVE_TENANT_ID: ${{ secrets.ONEDRIVE_TENANT_ID }}
        ONEDRIVE_CLIENT_ID: ${{ secrets.ONEDRIVE_CLIENT_ID }}
        ONEDRIVE_CLIENT_SECRET: ${{ secrets.ONEDRIVE_CLIENT_SECRET }}
        ONEDRIVE_USER_EMAIL: ${{ secrets.ONEDRIVE_USER_EMAIL }}
        ONEDRIVE_ROOT_PATH: ${{ secrets.ONEDRIVE_ROOT_PATH }}
        ONEDRIVE_INDEX_URL: ${{ secrets.ONEDRIVE_INDEX_URL }}
        
      run: |
        python app.py
    - name: Update Repo And Push
      run: |
        git config --global user.email "kamino@imea.me"
        git config --global user.name "kamino"
        git add .
        git commit -m "update by github actions"
        git push origin main 
