name: Update Favorite Video List

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Python Scripts
      env:
        UID: ${{ secrets.UID }}
        IMAGE_SERVER_API: ${{ secrets.IMAGE_SERVER_API }}
        IMAGE_SERVER_KEY: ${{ secrets.IMAGE_SERVER_KEY }}
      run: |
        python update_video.py